chore: update workflow

diff --git a/.github/workflows/sync-to-private.yaml b/.github/workflows/sync-to-private.yaml
--- a/.github/workflows/sync-to-private.yaml
+++ b/.github/workflows/sync-to-private.yaml
@@ -56,23 +56,20 @@ jobs:
                   git config user.name "Beezy the bot"
                   git config user.email "marketing@speakeasy.com"
 
-                  # Rebase against latest main to avoid conflicts
-                  git pull origin ${BRANCH} --rebase
-
                   git add .
 
                   if git diff --cached --quiet; then
-                    echo "No changes to sync"
-                    echo "Nothing synced." >> $GITHUB_STEP_SUMMARY
-                    exit 0
+                  echo "No changes to sync"
+                  echo "Nothing synced." >> $GITHUB_STEP_SUMMARY
+                  exit 0
                   fi
 
                   git commit -m "Sync open source content 🐝 (from $GITHUB_SHA)"
 
                   if ! git push origin ${BRANCH}; then
-                    echo "❌ Push to private repo failed!" >> $GITHUB_STEP_SUMMARY
-                    echo "Please check for conflicts or access issues." >> $GITHUB_STEP_SUMMARY
-                    exit 1
+                  echo "❌ Push to private repo failed!" >> $GITHUB_STEP_SUMMARY
+                  echo "Please check for conflicts or access issues." >> $GITHUB_STEP_SUMMARY
+                  exit 1
                   fi
 
                   COMMIT_SHA=$(git rev-parse HEAD)
@@ -84,14 +81,14 @@ jobs:
                   echo "**Grouped file changes:**" >> $GITHUB_STEP_SUMMARY
 
                   git diff --cached --name-status | awk '
-                    {
+                  {
                       split($2, parts, "/");
                       folder = parts[1];
                       if (current != folder) {
-                        if (current != "") print "" >> ENVIRON["GITHUB_STEP_SUMMARY"];
-                        print "#### `" folder "/`" >> ENVIRON["GITHUB_STEP_SUMMARY"];
-                        current = folder;
+                      if (current != "") print "" >> ENVIRON["GITHUB_STEP_SUMMARY"];
+                      print "#### `" folder "/`" >> ENVIRON["GITHUB_STEP_SUMMARY"];
+                      current = folder;
                       }
                       print $0 >> ENVIRON["GITHUB_STEP_SUMMARY"];
-                    }
+                  }
                   '
